talker: "echo"
talker_openai: "echo"
language: "jk"              
start_wav: "/root/unitree_2025_08_14/src/L2/scripts/alb_llm/tts_1.wav"
wakeup_wav: "/root/unitree_2025_08_14/src/L2/scripts/alb_llm/tts_1.wav"
openai_key: "sk-s5Xtn2xtarj0wrhQ8qZZmTdUh7xO0LM3DHXAmMevx0W8Cp8l"

# Use closeai proxy by default (can be overridden by ROS/env)
openai_base: "https://api.openai-proxy.org"

# Audio paths for different languages
zh_ready_wav: "/root/unitree_2025_08_14/src/L2/scripts/alb_llm/jk_ready.wav"
zh_zaine_wav: "/root/unitree_2025_08_14/src/L2/scripts/alb_llm/jk_zaine.wav"

en_ready_wav: "/root/unitree_2025_08_14/src/L2/scripts/alb_llm/en_ready.wav"
en_zaine_wav: "/root/unitree_2025_08_14/src/L2/scripts/alb_llm/en_here.wav"

jk_ready_wav: "/root/unitree_2025_08_14/src/L2/scripts/alb_llm/jk_ready.wav"
jk_zaine_wav: "/root/unitree_2025_08_14/src/L2/scripts/alb_llm/jk_zaine.wav"

# Knowledge Base (Dictionary: keyword -> response)
knowledge:
  "握个手吧，打个招呼": |
    好呀！yoyo很高兴见到你！
